
#version 460

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(std430, binding = 2) buffer SSB
{
    uint ssb[];
};

layout(binding = 3) uniform UBO
{
    uint Nx;    // Image width
    uint Ny;    // Image height
};

void main()
{
	uint x = gl_GlobalInvocationID.x;
    uint y = gl_GlobalInvocationID.y;

    if (x < Nx && y < Ny)
    {
        uint idx = (y * Nx) + x;    // flatten grid


        ssb[idx] = ((ssb[idx] & 0xFFFFFFFF) == 0xFFFFFFFF) ? 0xFFFFFFF0 : 0; // Foreground (1) has distance 0, background (0) has ∞

    }
}